### ISSUE TITLE
Project not starting up on my computer

### ISSUE THREAD

**Issue by olumidayy** [codeforcauseorg/pledge#10]
I want to preview the project as the README.md directed, I ran all commands that i was supposed to, or at least all that i could. I saw somewhere that i can't use nvm on my windows computer so i couldn't run the command(s) that involved it.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'serve'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v13.1.0
4 verbose run-script [ 'preserve', 'serve', 'postserve' ]
5 info lifecycle pledge@0.1.0~preserve: pledge@0.1.0
6 info lifecycle pledge@0.1.0~serve: pledge@0.1.0
7 verbose lifecycle pledge@0.1.0~serve: unsafe-perm in lifecycle true
8 verbose lifecycle pledge@0.1.0~serve: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\OLUMIDE\Desktop\pledge\node_modules\.bin;C:\Users\OLUMIDE\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\OLUMIDE\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\nodejs;C:\Program Files\Microsoft VS Code\bin;C:\flutter\bin;C:\Users\OLUMIDE\AppData\Local\Android\Sdk\platform-tools;C:\Users\OLUMIDE\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\OLUMIDE\AppData\Local\Programs\Python\Python37;C:\Users\OLUMIDE\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\OLUMIDE\AppData\Roaming\npm;?C;C:\Program Files\Git\flutter\bin;C:\Program Files\PostgreSQL\12\bin;C:\Program Files\PostgreSQL\12\data;C:\flutter\bin;C:\Users\OLUMIDE\AppData\Local\Android\Sdk\platform-tools;C:\Users\OLUMIDE\AppData\Local\Android\Sdk\emulator;C:\Program Files\heroku\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle pledge@0.1.0~serve: CWD: C:\Users\OLUMIDE\Desktop\pledge
10 silly lifecycle pledge@0.1.0~serve: Args: [ '/d /s /c', 'gatsby serve' ]
11 silly lifecycle pledge@0.1.0~serve: Returned: code: 7  signal: null
12 info lifecycle pledge@0.1.0~serve: Failed to exec serve script
13 verbose stack Error: pledge@0.1.0 serve: `gatsby serve`
13 verbose stack Exit status 7
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid pledge@0.1.0
15 verbose cwd C:\Users\OLUMIDE\Desktop\pledge
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
18 verbose node v13.1.0
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 7
22 error pledge@0.1.0 serve: `gatsby serve`
22 error Exit status 7
23 error Failed at the pledge@0.1.0 serve script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 7, true ]
```

Above is the complete log from the run

**Comment by anujarora0502** [comment]
You should install nvm first

**Comment by krnblni** [comment]
Try running "npm install" before, "gatsby develop"

**Comment by olumidayy** [comment]
alright
